[package]
name = "simple-rpc-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpc-discord = { path = "../../" }
dotenv = "0.15.0"
tokio = "1.21.2"
